name: Test Run

on:
  workflow_dispatch:
    inputs:
      test_class:
        description: 'Test class or file to run (e.g., tests/test_example.py::TestClassName)'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-sugar
          pip install pytest-html
          pip install playwright
          playwright install
      - name: Run tests
        run: |
          if [ -z "${{ github.event.inputs.test_class }}" ]; then
            pytest --maxfail=1 --disable-warnings -q --html=report.html --self-contained-html
          else
            pytest ${{ github.event.inputs.test_class }} --maxfail=1 --disable-warnings -q --html=report.html --self-contained-html
          fi
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report.html
