name: Test Run

on:
  workflow_dispatch:
    inputs:
      test_class:
        description: 'Test class or file to run (e.g., tests/test_example.py::TestClassName)'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest
          pip install playwright
          playwright install

      - name: Install Allure CLI
        run: |
          wget -qO- https://github.com/allure-framework/allure2/releases/latest/download/allure-2.21.0.zip > allure.zip
          unzip allure.zip -d allure
          sudo ln -s $PWD/allure/bin/allure /usr/bin/allure

      - name: Run tests and generate Allure report
        run: ./your-test-script.sh

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
